#!/usr/bin/env python
# coding: utf-8

"""This script is intended to convert raw He3 detector files (generated by
He3 readout system) to simple text csv files with ASCii data.

Simple usage:
python k15reader.py input_file_name > output_file_name


Author: Konstantin Shpakov, march 2021.
"""

import re
import os
import numpy as np
import datetime
import pytz


SLOW_CONTROL_DATA_COLUMNS = 11
SC_VAL_POS = {"voltage": 0, "current": 2}
TIMEZONE = pytz.timezone("Etc/GMT+3")


def get_raw_lines(filename):
    lines = None
    with open(filename, 'r') as fid:
        lines = fid.readlines()
    return lines


def get_col_num(raw_line):
    pattern = '([^\s]+)'
    cols = re.findall(pattern, raw_line)
    return len(cols)


def get_date(raw_line):
    date_separator = '.'
    date_pattern = '[\d]+[\.][\d]+[\.][\d]+'
    date = re.findall(date_pattern, raw_line)
    assert len(date) > 0, "No date stamp found in line '{}'".format(raw_line)
    assert len(date) < 2, "Too many date stamp found in line '{}'".format(raw_line)
    date = date[0]
    day, month, year = (int(word) for word in date.split(date_separator))
    return day, month, year


def get_time(raw_line):
    time_separator = ':'
    time_pattern = '([\d]+[:][\d]+[:][\d]+)'
    time = re.findall(time_pattern, raw_line)
    assert len(time) > 0, "No time stamp found in line '{}'".format(raw_line)
    assert len(time) < 2, "Too many time stamp found in line '{}'".format(raw_line)
    time = time[0]
    hour, min, sec = (int(word) for word in time.split(time_separator))
    return hour, min, sec


def get_time_stamp(raw_line, shift_seconds=0, tz=TIMEZONE):
    day, month, year = get_date(raw_line)
    hour, mins, sec = get_time(raw_line)
    date_and_time = datetime.datetime(year, month, day, hour, mins, sec, tzinfo=tz)
    shift = datetime.timedelta(seconds=shift_seconds)
    date_and_time += shift
    return date_and_time.timestamp()


def get_k15_line_tail(raw_line):
    pattern = '(\s[\d\s]+)$'
    match = re.search(pattern, raw_line)
    line_tail = match.group(0).strip()
    return line_tail


def get_k15_data(raw_lines, shift_seconds=0):
    rows = get_col_num(raw_lines[0])
    # -1 because date and time are separated
    rows -= 1
    points = len(raw_lines)
    data = np.ndarray(shape=(rows, points), dtype=np.int64)
    for point, raw_line in enumerate(raw_lines):
        timestamp = get_time_stamp(raw_line, shift_seconds=shift_seconds, tz=TIMEZONE)
        data[0, point] = timestamp
        line_tail = get_k15_line_tail(raw_line)
        for row, val in enumerate(int(word) for word in line_tail.split()):
            # keep first row for timestamp
            data[row + 1, point] = val
    return data


def get_slow_control_values(raw_line):
    pattern = '\s([+-]?[0-9]+[.][0-9]+)\s'
    values = re.findall(pattern, raw_line)
    return values


def get_slow_control_data(raw_lines, shift_seconds=0):
    rows = 0
    for line in raw_lines:
        rows = get_col_num(line)
        if rows > 1:
            assert rows == SLOW_CONTROL_DATA_COLUMNS, \
                "Wrong number of data columns. Expected {}, got {}." \
                "".format(SLOW_CONTROL_DATA_COLUMNS, rows)
            break
    # -1 because date and time are separated
    rows -= 1

    # store 3 values (datetime, voltage, current)
    rows_to_store = 3

    raw_lines = [line for line in raw_lines if get_col_num(line) > 1]
    points = len(raw_lines)
    data = np.zeros(shape=(rows_to_store, points), dtype=np.int64)

    for point, raw_line in enumerate(raw_lines):
        timestamp = get_time_stamp(raw_line, shift_seconds, tz=TIMEZONE)
        data[0, point] = timestamp
        values = get_slow_control_values(raw_line)
        data[1, point] = int(float(values[SC_VAL_POS["voltage"]]) * 1000)
        data[2, point] = int(float(values[SC_VAL_POS["current"]]) * 1000)
    return data


def test():
    filename = "Cf252-12-03-2021"
    raw_lines = get_raw_lines(filename)
    data_array = get_k15_data(raw_lines)
    delimiter = ','
    for idx in range(data_array.shape[1]):
        print(delimiter.join(str(val) for val in data_array[:, idx]))


def main():
    """Reads input He3-data file and outputs (print) x,y data line by line
    Usage: python k15reader.py input_file_name > output_file_name

    :return: None
    """
    import sys
    import os

    delimiter = ','

    # check inputs
    assert len(sys.argv) > 1, "Please specify file path/name."
    assert len(sys.argv) < 3, "Too many input parameters."

    if sys.argv[1] == "-h" or sys.argv[1] == "--help":
        print("Usage: python k15reader.py input_file_name > output_file_name\n")
        return

    assert os.path.isfile(sys.argv[1]), "No such file '{}'\n".format(os.path.abspath(sys.argv[1]))

    # read
    raw_lines = get_raw_lines(sys.argv[1])
    data = get_k15_data(raw_lines)

    # save
    # np.savetxt()
    for idx in range(data.shape[1]):
        print(delimiter.join(str(val) for val in data[:, idx]))


if __name__ == "__main__":
    main()
    # test()
